### ISSUE TITLE
Convert IMC to Class Based Views

### ISSUE THREAD

**Issue by ghickman** [incuna/dashboard#8]

**Comment by ghickman** [comment]
Need to find out how to do formsets in CBVs!

**Comment by mjtamlyn** [comment]
There's no general formset view yet but I did something on Eric with inline formsets that may be partially reusable.

**Comment by ghickman** [comment]
@mjtamlyn OMG there are _so_ many views in Eric. _gets barge pole_

**Comment by mjtamlyn** [comment]
There: https://bitbucket.org/incuna/eric/src/03f6958d53b9/eric/ofatumumab/base_views.py#cl-172
